# Run command pm2 start pmconfig.yml --env production
apps:
  - script: ./index.js
    name  : 'CACI'
    watch : true
    env   :
      NODE_ENV: development
    env_production:
      NODE_ENV: production